service: portfolio-messages

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-southeast-1
  versionFunctions: false
  tracing:
    lamda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ MessagesTable, Arn ]

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - http:
          path: messages/create
          method: post

resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: portfolio-messages-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: message
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: message
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: HASH