service: jp6rt-web-messages

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-southeast-1
  versionFunctions: false
  tracing:
    lamda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ MessagesTable, Arn ]

custom:
  emailEndpoint: jp01r7@gmail.com
  smsEndpoint: +639452743660

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - http:
          path: messages
          method: post

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/sns.yml)}