service: jp6rt-w3b-service

custom:
  stack: ${opt:stage, 'dev'}-jp6rt-w3b

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  versionFunctions: false
  tracing:
    lamda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::ImportValue": ${self:custom.stack}-messages-table-arn
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: "*"
  environment:
    region: ap-southeast-1
    messageTopicARN:
      "Fn::ImportValue": ${self:custom.stack}-message-topic-arn
    messageTable: ${self:custom.stack}-messages

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - http:
          path: messages
          method: post
  notify:
    handler: bin/notify
    events:
      - stream:
          type: dynamodb
          arn:
            "Fn::ImportValue": ${self:custom.stack}-messages-table-stream-arn
