AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Dynamo DB table for messages
Parameters:
  ApplicationName:
    Type: String
    Default: jp6rt-web
    Description: Application Name Reference

Resources:
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ApplicationName}-messages
      AttributeDefinitions:
        - AttributeName: message
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: message
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      StreamSpecification:
        StreamViewType: NEW_IMAGE
