AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Dynamo DB table for messages

Resources:
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: jp6rt-web-messages
      AttributeDefinitions:
        - AttributeName: message
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: message
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10