version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/golang:1.12.9
    steps:
      - checkout
      - run:
          name: Build create handler
          command: GO111MODULE=on GOOS=linux go build -ldflags="-s -w" -o bin/create handlers/create/main.go
      - run:
          name: Build notify handler
          command: GO111MODULE=on GOOS=linux go build -ldflags="-s -w" -o bin/notify handlers/notify/main.go
      - save_cache:
          key: build-cache-{{ .BuildNum }}
          paths:
            - ./bin
  deploy_resources:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    environment:
      STACK_NAME: "prod-jp6rt-web"
    steps:
      - checkout
      - run:
          name: Install pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py --user
            pip3 --version
      - run:
          name: Install aws cli
          command: |
            pip3 install awscli --upgrade --user
            export PATH=~/.local/bin:$PATH
            aws --version
            pip3 install --upgrade --user awscli
      - run:
          name: Deploy resources
          command: |
            export PATH=~/.local/bin:$PATH
            chmod +x ./deploy.sh
            ./deploy.sh
  deploy_service:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys: 
            - build-cache-{{ .BuildNum }}
      - run:
          name: Install serverless
          command: sudo npm install serverless -g
      - run:
          name: Deploy service
          command: sls deploy --stage prod

workflows:
  version: 2.1
  deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy_resources:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy_service:
          requires:
            - build
            - deploy_resources
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
